// @flow
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE'
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE'
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS'
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS'